### ISSUE TITLE
Compatibility and other things for latest C++ syntax, VS builds, etc

### ISSUE THREAD

**Issue by YalekW5435** [sureandrew/SexyAppFramework#1]
Being in the popcap community/Bejeweled community for over 12 years and wanted to start doing some stuff with this framework, but:

Is this framework even compatible with the latest version(s) of the C++ syntax, and which now in VS, needs to include library files in the framework (for the linker) in order for a project to build? 
Also, the framework is *old*, from 1995-2005, from the bygone era of Windows 95-XP.  (XP people might luck out with this).  

The projects ive tried building with this even with the framework set as a startup project with proper configurations all fail to build because of the above (and below issues).

Also, DirectDraw is bygone, and some D3D things need to be checked out, such as D3D11 and D3D12 support (which somehow the framework can allow even with the class variables mWidth and mHeight being able to be set to 4K maybe, because it can be any resolution which is a great start, as the framework somehow was ahead of its time with the infinite resolution settings you can set), and some other things.  There is an issue with a D3D8 header as its trying to include a nonexistent header known as "d3d8caps.h".  As to probably reason that, D3D8 is only a legacy component on some Win10 OS's.

Unsure though if this version of the framework (dating to 2016), fixes those issues. 

I myself am not an expert at C++ but am aware enough to share these issues at forth.  Even though the current is 1.30.  

I am also unsure (and quite displeased) why this framework didnt make it to linux for the people there deserve this stuff.  

So those are the things ive noticed with this current version.

BTW, I think "sureandrew" = Andrew Stein, from Popcap himself.  :P.

**Comment by YalekW5435** [comment]
To add on to the frameworks incompatibility:  The current versions of Visual studio (I ofc am using vs2019 community)*requires*, and this is not an option, for every single .vcxproject, .vcproject, be upgraded and migrated to the latest standards and build requirements, regardless of what version you have.  You cannot say no to this in VS2019 community.  And if you jhit cancel, it will not open in those versions, just a blank IDE.

Theres a big problem with this and its because when you do that, some things get messed up and errors are caused.  Some projects in this framework also fail to completely upgrade and migrate at all, due to their settings.  

2.  And if you attempt to build anything with the settings configured the way they are, they will *all* fail, regardless.  Sorry folks, but you probably wont be able to build anything past 2010.  Even the tutorials and demos claim to help others build in the current configs.  Even setting the startup projects to which the "local windows debugger" changes to "start" >> guess what? It aint building.  Sorry to break the party to pieces, but this is how Visual studio had become since past 2010 or more.  I did see a columns thing that was built with this and that guy was lucky to build with the settings he had, because of 2008 era stuff.  But even opening that game, still required a massive update.  It ruins everything.

Hopefully Sureandrew can fix this massive issue in disguise, because its making us feel empty and have no where to go.

**Comment by YalekW5435** [comment]
![cap1](https://user-images.githubusercontent.com/23326973/101946437-f7aafa00-3bbc-11eb-9b03-c2d62948bf8e.png)

**Comment by YalekW5435** [comment]
Now: this does not mean your *entire* project will build.  I was able to build both the framework (as lib), and my project with as much accuracy as possible, even on Windows 10.

But theres an even BIGGER problem with VS when it tried to execute the following: Note: I dont have any additional code added as of yet, only a background color to fill in the window's color as a dark grey.

![image](https://user-images.githubusercontent.com/23326973/106169927-ed898e80-615d-11eb-8115-b24a7c6c5bd8.png)

and the reason being below:

![image](https://user-images.githubusercontent.com/23326973/106170057-114cd480-615e-11eb-8fc7-a8dc67b4fb87.png)

Nothing more than the fact that WE CANNOT BE USING DIRECTDRAW ON WINDOWS 10.

**Comment by YalekW5435** [comment]
And thus is why, at all costs, maintenance is 100% important.  Its just like the linux kernel, YOU MUST KEEP IT MAINTENANCED.

**Comment by rullinoiz** [comment]
you're getting this for free and popcap hasn't made a real casual game since 2009

**Comment by YalekW5435** [comment]
> 
> 
> you're getting this for free and popcap hasn't made a real casual game since 2009

What are you even blabbing about?  It looks like you havent read this issue fully.  It is to explain that MAINTENANCE to anything is required.

When you have windows 10 and you get something this old via the 90s and early 00s, guess what? YA CANT USE IT>>>Unless if one does a lot of code changes within a framework itself, just to make it compatible with modern OSes.  << Which im not doing because I dont have the time or motivation to.

Not only that, but it was also hard to get this here since Popcap's Acquisition to EA.  So techincally, your statement is shit.  And quite honestly, sounds like you need to research more about why maintenance is required.

Now you are correct that yes, we are getting this for free, but the problem is: It wont work with modern OS capabilties as Direct Draw is OBSOLETE.  You could probably run this framework on a virtual machine, but that is still inefficient with the issue in question.  Besides, I cannot contact sureandrew anywhere.  No email, nothing.

Please dont say that again.  

Yalek.
