### ISSUE TITLE
A person through Assembla is holding newer versions of this static library (1.34 and above) and is trying to secure this repo away from github

### ISSUE THREAD

**Issue by YalekW5435** [sureandrew/SexyAppFramework#3]
Please pardon the previous 2 issues I had with this thing...They are now resolved.  But there is something else I found that's extremely suspicious.
 I found out 1.30 is not the latest version of this framework, or more specifically, static library.  A repo was formed through Assembla, with this git cloned, and the new "owner"< natasdm01 is currently sealing it off from the public and trying to take ownership of it.  
The reasoning for this is Assembla's way of conducting business with its users.  It does it through a company-wide business strategy, sealing off community relations with users and only providing company-wide needs, not user needs.  

So, in essence, this new "person" named natasdm01 sealed off the later versions of this static library.  

https://app.assembla.com/spaces/sexy/wiki

When trying to access the SVN links, you are prompted with a similar prompt as to how you would log in to a local router's login pop-up window.  

The guy was planning on adding a ton of features, and combining the popular classes MemoryImage, Image, and DDImage, into a single class, which I believe based off of the root namespace's conversion macros, to be called "SexyImage".  He also was suggesting to provide us with some new pixel formats and shading techniques and pipeline techniques with these 3 base classes for post processing methods.

Also odd, he worked on this in 2009, making this repo more than 3 years late for release.  Lolhacksrule found a way to tackle the difficult task to release 1.34 to github.  

As for the end user, Im sorry to say you probably wont see newer versions pop out in time, especially to fix the issues of compatiblity with how fast windows is evolving.   Your games will still run, thankfully, but you will need to be patient.  What i'll do is provide a text document to submit for the author here for a pull request so this way the user can fully be able to operate in precise *detail* for this static library to be used.

![image](https://github.com/sureandrew/SexyAppFramework/assets/23326973/5584cf7e-add3-478a-92c4-cc5a5038be7f)

**Comment by ghost** [comment]
If you saw that login promt showed up, just enter a random username and password. It will automaticly take you to the repo.

**Comment by ghost** [comment]
Yeah frick this. I might just open a god dman pull request.

**Comment by ghost** [comment]
My pull request resovled this. So you might consider closing this issue.
